### ISSUE TITLE
Publishing the app to F-Droid

### ISSUE THREAD

**Issue by Matthieu-LAURENT39** [vishal2376/git-coach#10]
**Is your feature request related to a problem? Please describe.**
Some people (me included) don't use Google services, and as such don't use the play store.  
We therefore need to manually install the app, which is pretty annoying for updates.

**Describe the solution you'd like**
Adding the app to F-Droid would allow installing and updating easily, as well as allow users to find the app by browsing the F-Droid store.
F-Droid requires app to not contain proprietary code, which seems to have been fixed in #3 

**Describe alternatives you've considered**
Installing the APK manually from github, which works but doesn't allow easy updating.

**Additional context**
There is a guide on how to get your app included in F-Droid [here](https://f-droid.org/docs/FAQ_-_App_Developers/#how-do-i-get-my-app-included).
You can either [generate the metadata yourself](https://f-droid.org/docs/Submitting_to_F-Droid_Quick_Start_Guide/), which takes some effort but makes inclusion a lot faster, or you can just [open an issue asking for inclusion](https://gitlab.com/fdroid/rfp/-/issues)

**Comment by vishal2376** [comment]
Got it! Adding the app to F-Droid for easier installation and updates sounds like a good plan.

Thanks @Matthieu-LAURENT39 for addressing the issue 🚀.

I'll check out the F-Droid inclusion process and see about generating metadata for the app.

**Comment by ghost** [comment]
It's on [F-droid](https://apt.izzysoft.de/fdroid/index/apk/com.vishal2376.gitcoach) . Use Izzy's repo.

**Comment by vishal2376** [comment]
> It's on [F-droid](https://apt.izzysoft.de/fdroid/index/apk/com.vishal2376.gitcoach) . Use Izzy's repo.

Thanks @rozari0

**Comment by vishal2376** [comment]
F-Droid Link Added

**Comment by Matthieu-LAURENT39** [comment]
Adding it to the main repo would eventually be nice, but that does the trick, thanks!

**Comment by vishal2376** [comment]
@Matthieu-LAURENT39 After struggling for two days, I finally created a merge request today. However, I encountered a pipeline failed issue. Fortunately, someone else was able to fix the pipeline issue. 😄

Nevertheless, there are still a few remaining issues, and I'm unsure about the next steps to take.

Here is the link [Merge Request: Git Coach](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/13589)

**Comment by Matthieu-LAURENT39** [comment]
Hmmm, the error seems that it's downloading the binaries from github (as configured in the metadata), and that binary doesn't match the one that F-Droid compiled themselves (`2023-08-19 15:32:04,262 ERROR: Could not build app com.vishal2376.gitcoach: compared built binary to supplied reference binary but failed`)

Anyways, i think you could probably fix this by just not supplying pre-built binaries in the metadata, and it should just use the APK built on F-Droid's side.
This has the disadvantage of not having your signature for the APK, but it's an easy fix.

Otherwise, you can try to work out why the build on F-Droid's side differs from the one you provide on github.

If you want more details, check [the F-Droid page about reproducible builds](https://f-droid.org/docs/Reproducible_Builds/). Your current case is you have binaries-metadata, but the build isn't reproducible, so the app publishing is aborted.

**Comment by marek22k** [comment]
Is there any news about the app being included in the official F-Droid repo? The MR at F-Droid was closed due to inactivity. In addition, the F-Droid button in the README is incorrect. IzzyOnDroid has an [extra button](https://gitlab.com/IzzyOnDroid/repo#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) for his repo.
