### ISSUE TITLE
Adding Localization Support

### ISSUE THREAD

**Issue by vishal2376** [vishal2376/git-coach#11]
| Language  | Lesson Translation | App Translation |
|------------------|-------------------|-----------------|
| Russian              | 95%               | ✔              |
| Brazilian/Portuguese | ✔                 | ✔              |
| German               | ✔                 | ✔              |
| Spanish              | 90%               | ✔              |
| Italian              | ✔                 | ✔              |

**Note**:exclamation: : These translations have been generated using [Crowdin](https://crowdin.com) . I have already rectified numerous incorrect command translations. 

However, there might still be some inaccuracies present. Please don't hesitate :smile: to report any problematic translations by creating a new issue or discuss in telegram group.

Join Telegram : https://t.me/gitcoach

Thank you :heart:

**Comment by alpha4041** [comment]
Hello, I'd be happy to translate everything in Italian because I just discovered this app and it's great. I just need the values-it folder to be initialized, but I recommend using Crowdin because it makes the job easier for the translators and the developers.

**Comment by vishal2376** [comment]
Thanks @alpha4041 :heart:  , for your interest in translating the Italian language.

I'm currently exploring ways to implement localization in an Android app. I'll be looking into **Crowdin** and attempting to implement it (*as long as it doesn't include any tracking elements*).

And yes, I definitely need assistance with translating the **Git lessons**, as they are separate JSON files (inside `assests` folder).

**Comment by alpha4041** [comment]
> Thanks @alpha4041 ❤️ , for your interest in translating the Italian language.
> 
> I'm currently exploring ways to implement localization in an Android app. I'll be looking into **Crowdin** and attempting to implement it (_as long as it doesn't include any tracking elements_).
> 
> And yes, I definitely need assistance with translating the **Git lessons**, as they are separate JSON files (inside `assests` folder).

okay, let me know you decide if to use a platform like Crowdin or else I'll do everything via a pull request

**Comment by vishal2376** [comment]
> > Thanks @alpha4041 ❤️ , for your interest in translating the Italian language.
> > I'm currently exploring ways to implement localization in an Android app. I'll be looking into **Crowdin** and attempting to implement it (_as long as it doesn't include any tracking elements_).
> > And yes, I definitely need assistance with translating the **Git lessons**, as they are separate JSON files (inside `assests` folder).
> 
> okay, let me know you decide if to use a platform like Crowdin or else I'll do everything via a pull request

Sure, I will inform you about it within a week.

**Comment by vishal2376** [comment]
@alpha4041 Now, I am using crowdin for translations.

Give me your email ID , I will add you in Crowdin as Translator.
So that you can verify and add the translations.

**Comment by alpha4041** [comment]
well ehm you aren't supposed to use Crowdin as an automatic translation platform, you're supposed to use it to get translations from translators..

**Comment by vishal2376** [comment]
Don't worry! If we found that there are a lot of incorrect translations , we will rectify it.

Translators are paid on crowdin and getting free community translators for every language isn't so easy.

But if you want to want to correct translations. You can do with pull request or by Crowdin platform(I will add you, if you want).

Join telegram discussion group: https://t.me/gitcoach
