### ISSUE TITLE
4.2

### ISSUE THREAD

**Issue by traviszech** [vishal2376/git-coach#16]
**Describe the bug**
4.2 is not on the releases page of GitHub though it is on the tags page.

**To Reproduce**
1. Go to the GitHub page
2. Click on releases
3. No 4.2 
4. Then hit tags
5. There's 4.2

**Comment by vishal2376** [comment]
Please check release page again. Release v4.2 was uploaded 2 months ago.

Here is the link:
https://github.com/vishal2376/git-coach/releases/tag/v4.2

![image](https://github.com/vishal2376/git-coach/assets/38159691/bc957517-ff66-4933-99e5-5e906ba710fc)
