### ISSUE TITLE
Turkish Translation Support

### ISSUE THREAD

**Issue by vishal2376** [vishal2376/git-coach#18]
If anyone wants to translate, they can join the project and contribute to translations.

Invitation link: [Telegram Group](https://t.me/gitcoach/) (Check pinned messages)

Crowdin Translation Project: https://crowdin.com/project/git-coach

**Comment by IzzySoft** [comment]
@vishal2376 would be a good idea to advertise the Crowdin URL at the Readme, so others can find it easily if they want to contribute translations 😉
