### ISSUE TITLE
Chinese translation support 

### ISSUE THREAD

**Issue by weiyuhl** [vishal2376/git-coach#20]
I hope this app can support Chinese, thank you

**Comment by vishal2376** [comment]
I will definitely try , if it's possible for me 😀

**Comment by weiyuhl** [comment]
> I will definitely try , if it's possible for me 😀

thank you👍

**Comment by vishal2376** [comment]
![image](https://github.com/vishal2376/git-coach/assets/38159691/0a0c639d-129e-4ed6-b929-42e91ffe026d)

### Chinese translation done.

## Changes will be reflected in next upcoming app update (**Git Coach v5.0**)
