### ISSUE TITLE
Material Icon

### ISSUE THREAD

**Issue by saltsoftdrink** [vishal2376/git-coach#25]
Improve the monochrome icon it looks like a bug or error reduce the size and enhance it

**Comment by vishal2376** [comment]
Duplicate Issues #17 

It will be fixed in next release

**Comment by saltsoftdrink** [comment]
> Duplicate Issues #17
> 
> It will be fixed in next release

Please don't forget

**Comment by vishal2376** [comment]
@saltsoftdrink Icon issue fixed

Enjoy next update, Git Coach v5.1 (available soon on Google play store)
