### ISSUE TITLE
Added support for Chinese translation of exercises in QUIZ

### ISSUE THREAD

**Issue by weiyuhl** [vishal2376/git-coach#29]
It is recommended that the practice language in QUIZ be synchronized with the Chinese translation.  I can assist if needed.  Thanks!

**Comment by vishal2376** [comment]
The reason for not translating is that the quizzes are mixed with git commands, which can also be translated automatically. Therefore, I don't want to translate the Git commands (as they might change the meaning)

**Comment by vishal2376** [comment]
There are around 150 questions in QUIZ
150 x 4 option = 600 options
Total strings: 600+150 = 750

So there are almost 500 strings of translation required for only 1 language. (Assuming 250 strings are git commands.)

**Comment by vishal2376** [comment]
If you still want to translate it, then go ahead and copy file from `assets/en/git_quiz.json` to the `assets/zh` folder and start translating. (Remember, You are not obliged to do it)

> **Close this issue** if you don't want to translate.

**Comment by lhzkml2512** [comment]
Hello, sorry, I just saw it.
In fact, I have read the translation of the entire app, but as far as Chinese is concerned, it is not very easy to understand. If possible, I might translate some parts in a simple and easy-to-understand way. Can you take a look at it?

**Comment by lhzkml2512** [comment]
> If you still want to translate it, then go ahead and copy file from `assets/en/git_quiz.json` to the `assets/zh` folder and start translating. (Remember, You are not obliged to do it)
> 
> > **Close this issue** if you don't want to translate. 

Hello, sorry, I just saw it.
In fact, I have read the translation of the entire app, but as far as Chinese is concerned, it is not very easy to understand. If possible, I might translate some parts in a simple and easy-to-understand way. Can you take a look at it?

**Comment by weiyuhl** [comment]
> If you still want to translate it, then go ahead and copy file from `assets/en/git_quiz.json` to the `assets/zh` folder and start translating. (Remember, You are not obliged to do it)
> 
> > **Close this issue** if you don't want to translate. 

Hello, sorry, I just saw it.
In fact, I read the translation of the entire app, but in terms of Chinese, it is not very easy to understand. If possible, I might translate some parts in a simple and easy-to-understand way. Can I translate it like this?

**Comment by vishal2376** [comment]
yeah sure

**Comment by weiyuhl** [comment]
> yeah sure

I have time to complete the translation these days, but now I am busy with new things, so I don’t have time to complete the translation as soon as possible. I will submit the PR as soon as possible after the later translation is completed.
Thank you
