### ISSUE TITLE
Bad German Translation

### ISSUE THREAD

**Issue by m3gamichi** [vishal2376/git-coach#33]
Hi i foind some erors in the German Translation:
![IMG_20241004_120423](https://github.com/user-attachments/assets/1656260a-7518-4499-b831-75a1cce33a34)
![IMG_20241004_120029](https://github.com/user-attachments/assets/161bd678-4d8e-4fd5-a68d-4f77791d50cf)
![IMG_20241004_120002](https://github.com/user-attachments/assets/570e314d-318f-40e2-ba8e-e3dcf628b011)
![IMG_20241004_115904](https://github.com/user-attachments/assets/7c90cc9c-d865-46d0-aef2-beb6510096a0)
![IMG_20241004_115835](https://github.com/user-attachments/assets/3ccf2a60-7db8-4c1b-b5a1-51ff8154225e)

Realy cool App :)

**Comment by vishal2376** [comment]
Thanks for reporting translations issues.

These all translations are generated by machine. I can't fix all translation as i don't know german language. 

If you can provide translattion of corresponding text, then it can fixed in new update

**Comment by m3gamichi** [comment]
Okay, great, how can I help you with translating?
Im a German Dude;)
