### ISSUE TITLE
Use custom markup files

### ISSUE THREAD

**Issue by GrimPixel** [vishal2376/git-coach#4]
**Is your feature request related to a problem? Please describe.**
It is good for learning anything, not limited to Git.

**Describe the solution you'd like**
Import own markup files to learn, with the ability ofo customising all the markup syntax to support different markdown dialects and other markup languages.

**Comment by vishal2376** [comment]
What are you expecting? Can you explain a little bit more with example.

**Comment by GrimPixel** [comment]
I would like to use custom files in a markup language to learn. It could be other programming languages; it could be other subjects.

**Comment by vishal2376** [comment]
Basically you want a markup language reader which can read imported (.md) files.

**Comment by GrimPixel** [comment]
Others like AsciiDoc as well, to be precise. In the ideal case, all the syntax can be customised.
