### ISSUE TITLE
Feature: Community Tab

### ISSUE THREAD

**Issue by vishal2376** [vishal2376/git-coach#5]
#### Question and Answer
-  Allow users to ask questions related to Git and have other community members provide answers and solutions. 

- Implement a search functionality to easily find relevant questions and answers.

---
### :speech_balloon: Comment down below if you have more ideas like post,discussion form etc.

**Comment by ironcrush2006** [comment]
How do you make projects from  c++

**Comment by vishal2376** [comment]
Sorry @ironcrush2006 , this issue is only created for user  feedbacks related to Android app (Git Coach).

But you can ask your doubts on telegram.
Telegram : https://t.me/vishal2376

**Comment by Matthieu-LAURENT39** [comment]
Won't this require quite a bit of moderation?
