### ISSUE TITLE
Just some praise

### ISSUE THREAD

**Issue by summersab** [vishal2376/git-coach#6]
I wanted to thank you for this app. I'm a git amateur, and I often forget the exact syntax of certain commands. Your app gives short, clear descriptions and lists some of the top commonly-used commands - that makes it incredibly easy to use.

It reminds me of the "Mug of vi," a vi reference mug that used to be sold on ThinkGeek (now defunct, but I thankfully have an original).

Thanks again!

**Comment by vishal2376** [comment]
Hi @summersab 

Thanks a lot for the review. I'm glad that my app is useful for you, especially if you're new to using Git. It can be frustrating to remember the right commands, but I'm happy to hear that my app's clear descriptions and the list of commonly-used commands are making it really easy for you to use.

You just made my day :smiley:
