### ISSUE TITLE
Make the ui smaller or correspondant with system dpi (screen size) settings.

### ISSUE THREAD

**Issue by Anonymous2716** [vishal2376/git-coach#7]
**Is your feature request related to a problem? Please describe.**
Well I use a higher DPI , small screen size ui on my phone. If you could make the ui more small the animations would look great as I could read more without scrolling much. Right now it takes half of the screen when scrolling. 

Also I don't know why you put a share button right next to the command but a copy button is helpful for me. Right now isn't a problem but Could you add toggle button to switch between copy and share , or do what you like , just letting you know.

**Comment by vishal2376** [comment]
@Anonymous2716 Thank you for addressing this issue.

1. It would be really helpful if you could provide screenshot of the first issue. 

2. Yes, I am also thinking replacing 'share' with the 'tap to copy' command."

**Comment by Anonymous2716** [comment]
@vishal2376  

![Screenshot_2023-07-27_00-16-58](https://github.com/vishal2376/git-coach/assets/78570872/34f3dbe6-05a3-4586-8be8-38e63ee7057f)

This UI elements are a little bigger than it should be I think. My screen DPI is set to 500 and my display size is 720x1600.  I wish I could show comparison of how similar ui looks like.

**Comment by Anonymous2716** [comment]
If you feel like it fix it. If not that's okay. Application works great. You can close it if you want.

**Comment by vishal2376** [comment]
@Anonymous2716 Don't worry , i am trying to reduce the size as much as possible.

**Comment by Rom1-GoPlay** [comment]
In my case, the text of explanations looks a bit small (commands are in a good size).
![Screenshot_20230731_134250_Git Coach.jpg](https://github.com/vishal2376/git-coach/assets/131159819/cbf75a4d-7b45-4296-bc58-c4198671d8f5)

I don't know exactly what is my screen size, but it is around 17cm (diagonal)
My phone is a Galaxy A51 (samsung).

Everything in this app is readable and beautiful but it is just a little uncomfortable.

**Comment by vishal2376** [comment]
@Rom1-GoPlay I am redesigning the lesson content, and there will also be an option to change the font size so that anyone can adjust it according to their needs.

**Comment by Rom1-GoPlay** [comment]
> @Rom1-GoPlay I am redesigning the lesson content, and there will also be an option to change the font size so that anyone can adjust it according to their needs.

Amazing !!

**Comment by vishal2376** [comment]
- Card Size spacing reduced 
- Searchbar will hide when you scroll
- Font size can be changed (See Demo https://github.com/vishal2376/git-coach/issues/8#issuecomment-1678776880 )
